name: jre_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_messaging: ^14.6.8
  cloud_firestore: ^4.9.2

  # BLoC Pattern
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.5
  json_annotation:


  # Dependency Injection
  get_it: ^7.6.4

  # Local Storage
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  readmore: ^3.0.0

  # Notifications

  # Permissions
  permission_handler: ^11.0.0

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  connectivity_plus: ^4.0.2
  shared_preferences_helper:
  flutter_screenutil: ^5.9.3
  http:
  get:
  fluttertoast: ^8.1.2
  auto_size_text:
  dartz:
  either_dart:
  shimmer:
  get_storage:
  provider:
  badges:



dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  build_runner:
  json_serializable:

  mocktail: ^1.0.0
  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/images/
    - assets/flags/
    - assets/translations/


