import '../../../model/home/proparty_model.dart';

class PropertyRepository {
  // This would normally fetch from an API or database
  Future<List<Property>> getProperties() async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 800));

    return [
      Property(
        rating: 5,
        id: '1',
        title: 'Modern Apartment',
        price: 267000,
        location: 'New York, NY',
        locationCode: '2BW',
        beds: 4,
        baths: 3,
        kitchens: 1,
        imageUrl: 'assets/images/apartment1.jpg',
        type: 'Apartment',
        name: 'Khaothong Terrace 1',
        country: 'Krabi Thailand',
        sqft: 6575,
      ),
      Property(
        id: '2',
        title: 'Luxury Villa',
        price: 550000,
        location: 'Miami, FL',
        locationCode: '3CV',
        beds: 5,
        baths: 4,
        kitchens: 2,
        imageUrl: 'assets/images/villa1.jpg',
        type: 'Villa',
        name: 'Khaothong Terrace 1',
        country: 'Krabi Thailand',
        sqft: 6575,
        rating: 5,

      ),
      Property(
        id: '3',
        title: 'Family House',
        price: 320000,
        location: 'Austin, TX',
        locationCode: '4FH',
        beds: 4,
        baths: 2,
        kitchens: 1,
        imageUrl: 'assets/images/house1.jpg',
        type: 'House',
        name: 'Khaothong Terrace 1',
        country: 'Krabi Thailand',
        sqft: 6575,
        rating: 5,
      ),
      Property(
        id: '4',
        title: 'Modern Villa',
        price: 620000,
        location: 'Los Angeles, CA',
        locationCode: '5MV',
        beds: 6,
        baths: 5,
        kitchens: 2,
        imageUrl: 'assets/images/villa2.jpg',
        type: 'Villa',
        name: 'Khaothong Terrace 1',
        country: 'Krabi Thailand',
        sqft: 6575,
        rating: 5,
      ),
      Property(
        id: '5',
        title: 'Studio Apartment',
        price: 175000,
        location: 'Chicago, IL',
        locationCode: '1SA',
        beds: 1,
        baths: 1,
        kitchens: 1,
        imageUrl: 'assets/images/apartment2.jpg',
        type: 'Apartment',
        name: 'Khaothong Terrace 1',
        country: 'Krabi Thailand',
        sqft: 6575,
        rating: 5,
      ),
      Property(
        id: '6',
        title: 'Countryside House',
        price: 290000,
        location: 'Boulder, CO',
        locationCode: '6CH',
        beds: 3,
        baths: 2,
        kitchens: 1,
        imageUrl: 'assets/images/house2.jpg',
        type: 'House',
        name: 'Khaothong Terrace 1',
        country: 'Krabi Thailand',
        sqft: 6575,
        rating: 5,
      ),
      // Add more sample properties
    ];
  }
}
